// file path: ~/DEVFOLD/SCRIPT-PITCHER/SRC/APP/LAYOUT.JS

import { Providers } from "./body/providers";

import "./globals.css";

// You can define your app's metadata here
export const metadata = {
  title: "My Awesome App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ width: "100vw", height: "100vh" }}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
